# Generated by Django 6.0.2 on 2026-02-22 01:29

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('icon', models.CharField(blank=True, help_text='Nombre de icono (opcional)', max_length=50, verbose_name='Ícono')),
                ('color', models.CharField(default='#3B82F6', help_text='Color en hexadecimal', max_length=7, verbose_name='Color')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('building', models.CharField(blank=True, max_length=100, verbose_name='Edificio')),
                ('floor', models.CharField(blank=True, max_length=50, verbose_name='Piso')),
                ('room', models.CharField(blank=True, max_length=50, verbose_name='Salón/Aula')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
            ],
            options={
                'verbose_name': 'Ubicación',
                'verbose_name_plural': 'Ubicaciones',
                'ordering': ['building', 'floor', 'room'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Código')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('quantity', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cantidad')),
                ('min_quantity', models.IntegerField(default=5, help_text='Alerta cuando esté por debajo', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cantidad mínima')),
                ('unit', models.CharField(default='unidad', max_length=50, verbose_name='Unidad de medida')),
                ('status', models.CharField(choices=[('available', 'Disponible'), ('in_use', 'En uso'), ('maintenance', 'En mantenimiento'), ('damaged', 'Dañado'), ('retired', 'Dado de baja')], default='available', max_length=20, verbose_name='Estado')),
                ('image', models.ImageField(blank=True, null=True, upload_to='articles/', verbose_name='Imagen')),
                ('barcode', models.CharField(blank=True, max_length=100, verbose_name='Código de barras')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio unitario')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='articles', to='inventory.category', verbose_name='Categoría')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='inventory.location', verbose_name='Ubicación')),
            ],
            options={
                'verbose_name': 'Artículo',
                'verbose_name_plural': 'Artículos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrower_name', models.CharField(max_length=200, verbose_name='Nombre del solicitante')),
                ('borrower_id', models.CharField(blank=True, max_length=50, verbose_name='ID/Matrícula')),
                ('borrower_contact', models.CharField(blank=True, max_length=100, verbose_name='Contacto')),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cantidad')),
                ('loan_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de préstamo')),
                ('due_date', models.DateTimeField(verbose_name='Fecha de devolución')),
                ('return_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de devolución real')),
                ('status', models.CharField(choices=[('active', 'Activo'), ('returned', 'Devuelto'), ('overdue', 'Vencido'), ('cancelled', 'Cancelado')], default='active', max_length=20, verbose_name='Estado')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loans_approved', to=settings.AUTH_USER_MODEL, verbose_name='Aprobado por')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='inventory.article', verbose_name='Artículo')),
                ('returned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loans_returned', to=settings.AUTH_USER_MODEL, verbose_name='Recibido por')),
            ],
            options={
                'verbose_name': 'Préstamo',
                'verbose_name_plural': 'Préstamos',
                'ordering': ['-loan_date'],
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('low_stock', 'Stock bajo'), ('overdue_loan', 'Préstamo vencido'), ('maintenance', 'Mantenimiento requerido'), ('other', 'Otro')], max_length=20, verbose_name='Tipo de alerta')),
                ('message', models.TextField(verbose_name='Mensaje')),
                ('is_read', models.BooleanField(default=False, verbose_name='Leída')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de lectura')),
                ('read_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Leída por')),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='inventory.article', verbose_name='Artículo')),
                ('loan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='inventory.loan', verbose_name='Préstamo')),
            ],
            options={
                'verbose_name': 'Alerta',
                'verbose_name_plural': 'Alertas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Movement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('entry', 'Entrada'), ('exit', 'Salida'), ('adjustment', 'Ajuste'), ('transfer', 'Transferencia'), ('loan', 'Préstamo'), ('return', 'Devolución')], max_length=20, verbose_name='Tipo de movimiento')),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cantidad')),
                ('previous_quantity', models.IntegerField(verbose_name='Cantidad anterior')),
                ('new_quantity', models.IntegerField(verbose_name='Cantidad nueva')),
                ('reason', models.TextField(verbose_name='Motivo/Razón')),
                ('reference', models.CharField(blank=True, help_text='Número de factura, orden, etc.', max_length=100, verbose_name='Referencia')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='inventory.article', verbose_name='Artículo')),
                ('from_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements_from', to='inventory.location', verbose_name='Desde ubicación')),
                ('to_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements_to', to='inventory.location', verbose_name='Hacia ubicación')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Movimiento',
                'verbose_name_plural': 'Movimientos',
                'ordering': ['-created_at'],
            },
        ),
    ]
