# Generated by Django 6.0.2 on 2026-02-24 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='purchase_date',
            field=models.DateField(blank=True, help_text='Fecha en que se adquirió el artículo', null=True, verbose_name='Fecha de Compra'),
        ),
    ]
