# Generated by Django 6.0.2 on 2026-02-28 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_article_purchase_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='supplier',
            field=models.CharField(blank=True, help_text='Lugar o proveedor donde se compró el artículo', max_length=200, null=True, verbose_name='Proveedor'),
        ),
    ]
