# Generated by Django 6.0.2 on 2026-03-02 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_article_supplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='Precio unitario'),
        ),
    ]
