# Generated by Django 6.0.2 on 2026-03-06 12:26

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_article_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AseoProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('quantity', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cantidad')),
                ('unit', models.CharField(choices=[('unidad', 'Unidad'), ('litro', 'Litro'), ('kg', 'Kilogramo'), ('galón', 'Galón'), ('rollo', 'Rollo'), ('paquete', 'Paquete'), ('bolsa', 'Bolsa')], default='unidad', max_length=50, verbose_name='Unidad')),
                ('min_quantity', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cantidad mínima')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aseo_productos_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aseo_productos', to='inventory.location', verbose_name='Ubicación')),
            ],
            options={
                'verbose_name': 'Producto de Aseo',
                'verbose_name_plural': 'Productos de Aseo',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AseoMovimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('entry', 'Entrada'), ('exit', 'Salida')], max_length=10)),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('previous_quantity', models.IntegerField()),
                ('new_quantity', models.IntegerField()),
                ('reason', models.CharField(default='Ajuste manual', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='inventory.aseoproducto')),
            ],
            options={
                'verbose_name': 'Movimiento de Aseo',
                'verbose_name_plural': 'Movimientos de Aseo',
                'ordering': ['-created_at'],
            },
        ),
    ]
